install:
  - ./install.sh

language: generic

matrix:
  include:

    - os: linux
      dist: trusty

    - os: osx
      osx_image: xcode9.2

notifications:
  email:
    on_failure: always
    on_success: never

sudo: required
